backend:
  name: github
  repo: peditx/releases
  branch: main
  auth_type: implicit
  app_id: Ov23lifHcrzFtVm5F3Zl

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "releases"
    label: "Releases"
    folder: "src/content/releases"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "The main title of the release."}
      - {label: "Description", name: "description", widget: "string", hint: "A short summary of the release."}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Hero Image (Optional)", name: "heroImage", widget: "image", required: false}
      
      # This field is now a code editor for pasting script content directly.
      - label: "Script Content (Optional)"
        name: "scriptContent"
        widget: "code"
        required: false
        default_language: "shell"
        allow_language_select: true
        hint: "Paste the content of your shell script here. This allows for direct editing."
        
      - {label: "Body", name: "body", widget: "markdown"}

