backend:
  name: github
  repo: peditx/releases
  branch: main
  auth_type: implicit
  app_id: Ov23lifHcrzFtVm5F3Zl

# --- THE FIX IS HERE ---
# We are changing where images are stored to align with Astro's best practices.
media_folder: "src/assets/uploads" # Media files will now be stored inside the src folder.
public_folder: "/src/assets/uploads" # The public URL will also point here now.

collections:
  - name: "releases"
    label: "Releases"
    folder: "src/content/releases"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - {label: "Script File URL", name: "scriptUrl", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
