backend:
  name: github
  repo: peditx/releases
  branch: main
  auth_type: implicit
  app_id: Ov23lifHcrzFtVm5F3Zl

# --- THE FINAL FIX IS HERE ---
# We are moving images back to the /public folder.
# This is the standard way to handle static assets that Astro should not process.
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "releases"
    label: "Releases"
    folder: "src/content/releases"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - {label: "Script File URL", name: "scriptUrl", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

